name: TarkMullAuth
version: '1.0.0'
main: com.tarkmull.auth.AuthPlugin
api-version: '1.21'
author: TarkMull
description: Красивая система регистрации и входа с автосессиями

commands:
  register:
    description: Зарегистрировать аккаунт
    usage: /register <пароль> <повтор_пароля>
  login:
    description: Войти в свой аккаунт
    usage: /login <пароль>
  changepassword:
    description: Сменить пароль от аккаунта
    usage: /changepassword <старый_пароль> <новый_пароль> <новый_пароль>
    aliases: [changepass, passwd]
  captcha:
    description: Ответить на пример при регистрации
    usage: /captcha <число>
    aliases: [cap]
